name: bodyguide server CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. JDK 설정
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
         
    # 3. config 폴더 생성 및 application.yml 작성
    - name: Create application.yml from Secret
      run: |
        mkdir -p config
        echo "${{ secrets.PROPERTIE }}" > config/application.yml
    
    # 4. Gradle 캐시 설정
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/wrapper
        key: gradle-wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: gradle-wrapper-${{ runner.os }}-

    # 5. Gradle로 빌드
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew clean build -x test --parallel --build-cache --configure-on-demand --no-daemon

    # 6. Docker 이미지 빌드
    - name: Build Docker Image
      run: |
        docker build -t dudungsil540/bodyguide-sv:latest .

    # 7. Docker Hub로 푸시
    - name: Push Docker Image to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - run: |
        docker push dudungsil540/bodyguide-sv:latest

    # 8. 배포 (API 서버만 업데이트)
    - name: Execute remote command over SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          PROJECT_DIR="/home/${{ secrets.SERVER_USER }}/bodyguide"

          echo "Navigating to project directory..."
          cd $PROJECT_DIR || exit 1

          echo "Pulling latest Docker image..."
          docker pull dudungsil540/bodyguide-sv:latest

          echo "Rebuilding and restarting API service..."
          docker-compose -f $PROJECT_DIR/docker-compose.yml up -d --no-deps --build api

          echo "Cleaning up unused images..."
          docker image prune -f

          echo "API service deployment completed successfully."
